module.exports = {
    GET_THERAPISTS: '/api/therapists',
    UPDATE_THERAPISTS: '/api/therapists/:therapist_id',
    DELETE_THERAPISTS: '/api/therapists/:therapist_id',
    GET_TESTIMONIALS: '/api/testimonials',
    CREATE_TESTIMONIALS: '/api/testimonials',
    UPDATE_TESTIMONIALS: '/api/testimonials/:testimonial_id',
    DELETE_TESTIMONIALS: '/api/testimonials/:testimonial_id',
    UPDATE_TESTIMONIAL_STATUS: '/api/testimonial_status/:testimonial_id',
    GET_EVENTS: '/api/events',
    CREATE_EVENT: '/api/events',
    UPDATE_EVENT: '/api/events/:event_id',
    DELETE_EVENT: '/api/events/:event_id',
    UPDATE_EVENT_STATUS: '/api/event_status/:event_id',
    LOGIN: '/api/login',
    LOGOUT: '/api/logout',
    REGISTER: '/api/register',
    SENDMAIL: '/api/sendmail',
    DASHBOARD: '/api/admin/dashboard',
    GET_DELETED_EVENTS: '/api/admin/deleted_events',
    GET_DELETED_TESTIMONIALS: '/api/admin/deleted_testimonials',
    GET_DELETED_USERS: '/api/admin/deleted_users',
    PERMANENTLY_DELETE_EVENT: '/api/admin/deleted_events/:event_id',
    PERMANENTLY_DELETE_TESTIMONIAL: '/api/admin/deleted_testimonials/:testimonial_id',
    PERMANENTLY_DELETE_USERS: '/api/admin/deleted_users/:user_id',
};