INSERT INTO events
(
    description,
    event_form,
    event_time,
    recurring_ind,
    important_fl,
    lk_event_type_id,
    lk_event_status_id,
    therapist_id,
    created_by,
    created_datetime
)
values
(
    ${description},
    ${eventForm},
    ${eventTime},
    ${recurringInd},
    ${importantFl},
    ${lkEventTypeId},
    ${lkEventStatusId},
    ${therapistId},
    ${createdBy},
    now()
);